version: "3.8"

services:
  core:
    build: ./core
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos
    environment:
      - VIDEO_DIR=/app/videos
      - ANALYTICS_URL=http://analytics:5010
    cap_add:
      - NET_ADMIN
    depends_on:
      - analytics
    networks:
      - core_network

  edge1:
    build: ./edge
    ports:
      - "5001:5001"
    volumes:
      - edge1_cache:/app/cache
      - ./logs:/logs
    environment:
      - EDGE_ID=edge1
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5001
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
      - SIMULATED_LATENCY=10ms
      - LOCATION=Helsinki
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - core
      - redis
    networks:
      - core_network
      - edge_network

  edge2:
    build: ./edge
    ports:
      - "5002:5002"
    volumes:
      - edge2_cache:/app/cache
      - ./logs:/logs
    environment:
      - EDGE_ID=edge2
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5002
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
      - SIMULATED_LATENCY=15ms
      - LOCATION=Stockholm
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - core
      - redis
    networks:
      - core_network
      - edge_network

  edge3:
    build: ./edge
    ports:
      - "5003:5003"
    volumes:
      - edge3_cache:/app/cache
      - ./logs:/logs
    environment:
      - EDGE_ID=edge3
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5003
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
      - SIMULATED_LATENCY=12ms
      - LOCATION=Oslo
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - core
      - redis
    networks:
      - core_network
      - edge_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - core_network
      - edge_network

  analytics:
    build: ./analytics
    ports:
      - "5010:5010"
    volumes:
      - ./logs:/logs
    environment:
      - LOG_DB=/logs/requests.db
      - REPORT_PATH=/logs/analytics_report.json
    depends_on:
      - redis
    networks:
      - core_network
      - client_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - edge1
      - edge2
      - edge3
    networks:
      - edge_network
      - client_network

  client:
    build: ./client
    ports:
      - "8080:80"
    networks:
      - client_network

volumes:
  edge1_cache:
  edge2_cache:
  edge3_cache:

networks:
  core_network:
    driver: bridge
  edge_network:
    driver: bridge
  client_network:
    driver: bridge
