version: '3.8'

services:

  core:
    build: ./core
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos
    environment:
      - VIDEO_DIR=/app/videos

  edge1:
    build: ./edge
    ports:
      - "5001:5001"
    volumes:
      - edge1_cache:/app/cache
      - ./logs:/logs          # shared logs folder
    environment:
      - EDGE_ID=edge1
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5001
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
    depends_on:
      - core
      - redis

  edge2:
    build: ./edge
    ports:
      - "5002:5002"
    volumes:
      - edge2_cache:/app/cache
      - ./logs:/logs          # same shared logs folder
    environment:
      - EDGE_ID=edge2
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5002
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
    depends_on:
      - core
      - redis

  edge3:
    build: ./edge
    ports:
      - "5003:5003"
    volumes:
      - edge3_cache:/app/cache
      - ./logs:/logs          # same shared logs folder
    environment:
      - EDGE_ID=edge3
      - CORE_URL=http://core:5000
      - REDIS_HOST=redis
      - PORT=5003
      - MAX_CACHE_SIZE=3
      - LOG_DB=/logs/requests.db
    depends_on:
      - core
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - edge1
      - edge2
      - edge3

volumes:
  edge1_cache:
  edge2_cache:
  edge3_cache: